# Generated by Django 5.2.8 on 2025-11-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_username'),
        ('inventory', '0004_alter_stockdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse assignment for warehouse staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='inventory.warehouse'),
        ),
    ]
