# Generated by Django 5.2.8 on 2025-11-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
