# Generated by Django 5.2.8 on 2025-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockdocument_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address for customer (Deliveries) or vendor address (Receipts)'),
        ),
        migrations.AlterField(
            model_name='stockdocument',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Vendor/Supplier name for Receipts, Customer name for Deliveries', max_length=255),
        ),
    ]
