# Generated by Django 5.2.8 on 2025-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockdocument_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdocument',
            name='doc_type',
            field=models.CharField(choices=[('receipt', 'Receipt (Incoming)'), ('delivery', 'Delivery Order (Outgoing)'), ('internal', 'Internal Transfer')], max_length=20),
        ),
    ]
