# Generated by Django 5.2.8 on 2025-11-22 08:00

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """Create default product categories."""
    ProductCategory = apps.get_model('inventory', 'ProductCategory')
    default_categories = [
        'Furniture',
        'Raw Material',
        'Consumable',
        'Electronics',
        'Tools',
        'Packaging',
        'Office Supplies',
        'Machinery',
        'Hardware',
        'Automotive',
    ]
    
    for category_name in default_categories:
        ProductCategory.objects.get_or_create(name=category_name)


def reverse_create_default_categories(apps, schema_editor):
    """Remove default categories if migration is reversed."""
    ProductCategory = apps.get_model('inventory', 'ProductCategory')
    default_categories = [
        'Furniture',
        'Raw Material',
        'Consumable',
        'Electronics',
        'Tools',
        'Packaging',
        'Office Supplies',
        'Machinery',
        'Hardware',
        'Automotive',
    ]
    
    ProductCategory.objects.filter(name__in=default_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alert threshold: Show low stock warning when stock goes below this value', max_digits=12),
        ),
        migrations.RunPython(create_default_categories, reverse_create_default_categories),
    ]
